apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-assist-deployment
spec:
  selector:
    matchLabels:
      app: version-assist
  replicas: 3
  template:
    metadata:
      labels:
        app: version-assist
    spec:
      containers:
        - name: version-assist
          image: iad.ocir.io/intpsftengt/va-repo/va-frontend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              value: "mongodb://mongo-service:27017/mydatabase"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: SUPER_ADMIN
              value: 'summethsusubros@gmail.com'    
---
apiVersion: v1
kind: Service
metadata:
  name: version-assist-service
spec:
  selector:
    app: version-assist
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP

  