apiVersion: v1
kind: Service
metadata:
  name: version-assist-service
spec:
  selector:
    app: version-assist
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-assist-deployment
spec:
  selector:
    matchLabels:
      app: version-assist
  replicas: 3
  template:
    metadata:
      labels:
        app: version-assist
    spec:
      containers:
        - name: version-assist
          image: iad.ocir.io/intpsftengt/va-repo/va-frontend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              value: "mongodb://mongo-service:27017/mydatabase"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: SUPER_ADMIN
              value: 'summethsusubros@gmail.com'     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: iad.ocir.io/intpsftengt/va-repo/va-mongo:1.0
          ports:
            - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: iad.ocir.io/intpsftengt/va-repo/va-redis:1.0
          ports:
            - containerPort: 6379
